### ISSUE TITLE
spatialEnhance error in vignette

### ISSUE THREAD

**Issue by ph329** [edward130603/BayesSpace#25]
Hi, thank you so much for this really interesting technique - really excited to try it out. In going through the vignette with the melanoma sample I get the following error when running spatialEnhance: 
``` {r}
melanoma.enhanced <- spatialEnhance(melanoma, q=4, platform="ST", d=7,
                                    model="t", nrep=10000, gamma=2,
                                    jitter_prior=0.3, jitter_scale=3.5,
                                    save.chain=TRUE)
```
``` {r}
Error in seq_len(ncol(deconv_PCs)) : argument must be coercible to non-negative integer
```
Any advice? I've gone through the vignette basically copy-pasting your code so not sure where the issue lies. Thank you!

**Comment by msto** [comment]
Hi @ph329,

Sorry to hear about the error. We've been pushing some changes to the repo over the past week or two; could you please check that the version you have installed is up to date? The latest version is 0.99.4, which you can check with `packageVersion()`.

```
> packageVersion("BayesSpace")
[1] ‘0.99.4’
```

**Comment by ph329** [comment]
Hi, thanks for the quick reply! I am indeed running 0.99.4, I just downloaded it today so it should be the latest repo.

**Comment by msto** [comment]
Hi @ph329,

We think we've resolved this. The default `burn.in` for `spatialEnhance()` is 10,000 iterations. Since the demo also set `nrep` to 10,000, all the MCMC iterations were being excluded when trying to average the enhanced PCs.

This was due to two issues:

1. The online docs were out of date; the example should additionally include the `burn.in` parameter. The online docs have been updated and the correct call is below. 

        melanoma.enhanced <- spatialEnhance(melanoma, q=4, platform="ST", d=7,
                                            model="t", gamma=2,
                                            jitter_prior=0.3, jitter_scale=3.5,
                                            nrep=1000, burn.in=100,
                                            save.chain=TRUE)

    (We also suggest using a smaller number of iterations (`nrep`) when trying the package out. While this won't yield good results in practice, the runtime will be much shorter as you're getting familiar with the functions.)

2. There was a small bug in our logic to catch cases where `burn.in` exceeded `nrep`; we used a strict inequality and missed the case where they were equal. We just pushed a fix in version 0.99.5.

Could you please update your installation and/or try calling `spatialEnhance()` with a specified `burn.in`, and let us know if you continue to encounter any issues? Thanks for catching this!

**Comment by ph329** [comment]
Hi @msto, thanks! It's working perfectly now (both in the vignette and on my own Visium data). The results look fantastic! Thanks again for your help.

**Comment by msto** [comment]
Great, glad it’s working well!
