### ISSUE TITLE
Speed issue of imputing all genes at the sub-spot level

### ISSUE THREAD

**Issue by ciciQ777** [edward130603/BayesSpace#41]
Dear BayesSpace authors,

Thanks for developing this tool. I have run BayesSpace for a ST dataset. However, the time for imputing 10 genes at the subspot level like tutorial is ok for me. But when I tried to impute all genes in the original dataset, it runs forever. All the parameters are set as the same as in the tutorial. 

Do you have any suggestions on this? Or is is appropriate to impute more than 2000 genes at the subspot level?

Thanks!

**Comment by edward130603** [comment]
Hi cici, there are a few things you can try that can reduce the runtime:

1. Run on only a subset of highly variable genes (HVGs) or spatially variable genes (SVGs) using the `feature_names` argument.
2. Set `nrounds` to 100. The default is to tune the number of boosting iterations for xgboost for better feature prediction at the cost of higher runtime.
3. Use `model = "lm"` to predict using linear regression instead of xgboost. Linear regression actually performs quite well in most cases.

**Comment by ciciQ777** [comment]
Thank you very much for your quick reply! I'll try this!
