### ISSUE TITLE
Something wrong with spatialCluster?

### ISSUE THREAD

**Issue by BinDuan** [edward130603/BayesSpace#46]
I tried the function "spatialPreprocess" for datasets "Human_DLPFC_spatialLIBD" used in the Figure 2 of your paper, but I get this message "Neighbors were identified for 0 out of 3639 spots.". Although it still works, the result is not as good as the result you showed in your paper. I wonder where is the problem?
Here are the codes:
colnames(test_coordinate2)<-c("row","col")
sce <- SingleCellExperiment(assays=list(counts=as(test_expression, "dgCMatrix")),
                            colData=test_coordinate2)

set.seed(102)
sce <- spatialPreprocess(sce, platform="Visium", 
                              n.PCs=15, n.HVGs=2000, log.normalize=T)

set.seed(149)
sce <- spatialCluster(sce, q=7, platform="Visium",
                           nrep=1000, burn.in=100
                           )

And the warning messages are below:
Neighbors were identified for 0 out of 3639 spots.

Fitting model...

Calculating labels using iterations 100 through 1000.

**Comment by edward130603** [comment]
I'm guessing the problem is the `test_coordinate2` coordinates that you provided might not be the right ones. We are using `row` and `col` to calculate neighbors rather than `imgrow` and `imgcol`. Both are part of the Space Ranger output, but `row` and `col` are better for defining the neighborhood geometry while `imgrow` and `imgcol` correspond to pixel locations on the image.

Following your code, with a few extra lines at the beginning:
```r
library(BayesSpace)

sce.orig = getRDS("2020_maynard_prefrontal-cortex", "151673")
test_coordinate2 = cbind(sce.orig$row, sce.orig$col)
test_expression = counts(sce.orig)
colnames(test_coordinate2)<-c("row","col")
sce <- SingleCellExperiment(assays=list(counts=as(test_expression, "dgCMatrix")),
                            colData=test_coordinate2)

sce <- spatialPreprocess(sce, platform="Visium",
                         n.PCs=15, n.HVGs=2000, log.normalize=T)

sce <- spatialCluster(sce, q=7, platform="Visium",
                      nrep=1000, burn.in=100
)
```

I get:
```
Neighbors were identified for 3638 out of 3639 spots.
Fitting model...
Calculating labels using iterations 100 through 1000.
```

**Comment by BinDuan** [comment]
Thanks for your reply, yes, now it works fine. However, here are two other questions:
1. You provided two initial clustering methods "mclust" and "kmeans", I wonder how to choose and which method you use in your article? I find that different initail clustering methods has significant influence on the results. It seems you didn't talk this in you paper.
2. Lots of space transcriptome data only provided pixel locations, that is "imgrow" and "imgcol", then how to get the corresponding "row" and "col" to suit your tool. 

Thanks again!
Best regards.

**Comment by edward130603** [comment]
1. We recommend using `"mclust"` as our default since BayesSpace can be thought of as an extension of mclust and it has worked well in our datasets so far. You can choose to initialize BayesSpace with the clustering of any other method (e.g. Walktrap, Louvain, Leiden, etc.). We just provided "kmeans" as one example, but you can input your own initialization via the `init` parameter.
2. For Visium data, the arrow row and column coordinates are in `tissue_positions_list.csv` which is part of the output from Space Ranger. For the older ST data, array row and col coordinates are the only ones available (no matching to image pixels). We have not adapted BayesSpace to work on data from other technologies yet, but may do so if there is demand.
Hope this helps!

**Comment by BinDuan** [comment]
It really helps. Thanks so much.

**Comment by PepsiZhu** [comment]
Hello,
I would like to inquire if the tool you mentioned has been developed, allowing for direct clustering analysis using imagecol and imagerow. Indeed, many of the downloaded spatial transcriptomics data only provide pixel positions. I look forward to your response. thanks
@edward130603
