### ISSUE TITLE
spatialEnhance stuck in endless loop

### ISSUE THREAD

**Issue by matthewdbradley** [edward130603/BayesSpace#49]
Expected Behavior: 
**sample:** A 10X Visium sample loaded as follows:
```
sample <- readVisium("sample/outs/") %>% spatialPreprocess(platform="Visium", n.PCs=40)
```

Observed Behavior:
After running qTune and qPlot to determine the optimal clustering (following the vignette), I ran spatialEnhance. 
```
sample.enhanced <- spatialEnhance(sample, q=11, platform="Visium", d=15,
+                                     model="t", gamma=3)
```
This launched my R session into what seemed like an endless loop. 

I tried once on a dedicated RStudio server (plentiful RAM and CPU), ran for about 4.5 hours.
I also tried once in an isolated HPC job ( 32 cores, 80 GB RAM just to be safe) and ran for 15 hours. 
Normal spatial clustering (q=11) and graph generation completed (non-interactively) in 21 minutes on this dataset, which contains 2436 spots and 542 MB of data. 

I interrupted this task on the interactive RStudio server using Ctrl+C, and a "sample.enhanced" object was copied to my global environment, along with the following warnings through the R console:

```
Warning messages:
1: In UseMethod("depth") :
  no applicable method for 'depth' applied to an object of class "NULL"
2: In UseMethod("depth") :
  no applicable method for 'depth' applied to an object of class "NULL"
3: In UseMethod("depth") :
  no applicable method for 'depth' applied to an object of class "NULL"
```
This object had the expected subplot graph when plotted with the appropriate function, but I'm currently unsure of how to reproduce this behavior. 

This seems related to this issue 
tidyverse/ggplot2#2514

**Comment by edward130603** [comment]
I'm not exactly sure of what the cause of the issue is right now. A few ideas:

1. Try running spatialEnhance with the `verbose = TRUE` flag. This will print the progress so it's easier to see what's happening.
2. Since your spot-level clustering took 21 min, I estimate the enhancement should take ~8.4 hours (21 min/60* 200 iterations/50 iterations * 6 subspots).
3. When you use ctrl+C to cancel, spatialEnhance will stop and return the partial results. I'm not sure what the warning is but assume it probably isn't the most relevant issue here. `spatialEnhance` does not use any ggplot plotting.

I think most likely the issue is it needs more runtime. The HPC node you submitted to might be slower for whatever reason.  I typically submit jobs to my HPC with 2 CPUs, 80G RAM and longer runtime. The whole script including enhancement will generally finish within 6-24 hours depending on size of data. 

Finally, I wanted to point out that it's a good idea to tune the `jitter_scale` parameter using a small number of reps before doing a compute run with 200k iterations. This is also a good chance to quickly tell if `spatialEnhance` is working correctly on your data. Some sample code to do this tuning:

```r
sce.enhanced <- spatialEnhance(sce, q=5, d=15, platform="Visium", verbose = T,
                               nrep=2500, #only 2500 iterations
                               burn.in = 100, #short burn-in
                               jitter_scale=5, #this is the paramter to tune
                               save.chain=T) #save chain so you can plot after
chain = mcmcChain(sce.enhanced, "Ychange")
print(chain) 
```
If the chain seems to stabilize to ~0.3 (anywhere from 0.25-0.4 is ok) then `jitter_scale` is good. If below 0.25, decrease `jitter_scale`. If above 0.4, increase `jitter_scale`. 

We'll try to add these details into the official vignettes soon to make our functions easier to use.

**Comment by matthewdbradley** [comment]
From your detailed response I was able to tune for my data and get a complete run. Thanks for the help, and the excellent package!
