### ISSUE TITLE
Error in visualizing spatial clusters

### ISSUE THREAD

**Issue by dak-wilson** [edward130603/BayesSpace#76]
Hi,

When using the clusterPlot() function to visualize the spatial clusters,  cluster assignments are not successfully labeled over the spatial locations.

Here is my code:

library(ggplot2)
library(Matrix)
library(tidyverse)
library(BayesSpace)
library(SingleCellExperiment)

count <- read.csv("counts.csv", check.names=F, stringsAsFactors=FALSE)
rowname <- count[,1]
count <- as.matrix(count)
row.names(count) <- rowname
colData <- read.csv("colData.csv",stringsAsFactors=FALSE,row.names = 1)
names(colData)[1] <- "row"
names(colData)[2] <- "col"

sce <- SingleCellExperiment(assays = list(counts=count), colData=colData)
sce <- spatialPreprocess(sce, platform="ST", n.PCs=7, n.HVGs=2000, log.normalize=TRUE)
sce <- qTune(sce, qs=seq(2, 20), platform="ST", d=7)
sce <- spatialCluster(sce, q=14, platform="ST", d=7,init.method="mclust", model="t", gamma=2,nrep=1000, burn.in=100,save.chain=TRUE)

clusterPlot(sce)

I'm not sure where the issue is,  could you suggest some solutions?

Thank you for your time!

[spatial_clusters.pdf](https://github.com/edward130603/BayesSpace/files/8338835/spatial_clusters.pdf)

**Comment by edward130603** [comment]
I think the problem is your distances are wrong right now, so the spots are super small, making the fill color invisible since all you are seeing is the grey border. This also means that the spatial clustering didn't work correctly, since it probably detected 0 neighbors for all spots. 

The issue is that your are using the pixel locations as the positional input while BayesSpace uses both the array coordinates and pixel locations. These are part of the default output from SpaceRanger in "tissue_positions_list.csv". If you have this, try loading in both sets of coordinates. Also, if you use BayesSpace's `readVisium` function to load the data, it should be in the right format.

**Comment by dak-wilson** [comment]
Thank you for the information, have a good one!
