### ISSUE TITLE
Cluster structure lost on enhancement

### ISSUE THREAD

**Issue by briglo** [edward130603/BayesSpace#77]
Hi, thanks for an awesome tool! I was making my way through some sections using the tutorial as a guide (optimising number o clusters and jitter scales) but on two of our 4 samples, cluster coherence was lost on spatial enhancement. For the other two the following approach worked a treat- but spatially enhanced clusters at least nominally resembled the low-res ones.

code is 

```{r) 
C1<-readVisium("PATH/TO/SPACERANGER/out")
indat<-spatialPreprocess(C1 platform="Visium", log.normalize=TRUE)
indat<-qTune(indat, qs=seq(2, 10), platform="Visium", d=12)
#qval 7 at/near elbow
indat <- spatialCluster(indat, q=qval, platform="Visium", d=12,init.method="mclust", model="t", gamma=2,nrep=1000, burn.in=100, save.chain=TRUE)
tmp.enhanced <- spatialEnhance(indat, q=qval, platform="Visium", d=12, model="t", gamma=2,jitter_prior=0.3,jitter_scale=2,nrep=1000, burn.in=100, save.chain=TRUE)
#mcmcChain(tmp.enhanced, "Ychange"): stabilises at 0.3 (although changing this didnt affect the outcome
clusterPlot(indat) | clusterPlot(tmp.enhanced)
```

gives the attached 
![cluster plot](https://user-images.githubusercontent.com/3935916/161893757-1ca1dcaa-e722-4e71-a9bb-d4ddd802e6a8.png)

I was wondering if you have seen this before. Is there a way around it/am i missing something/ or is there not enough structure in the data itself to support the clustering?- this is possible ; the section itself was more homogeneous

Thanks again and do feel free to redirect me (i did notice a similar looking thing can happen if coordinates are explicitly declared, but i didnt do that here).
Regards

**Comment by edward130603** [comment]
It's not immediately clear to me what went wrong here. Your code seems fine. I ran the code using your parameters on our data and did not notice anything strange. So I'm not sure what's going on, but the right hand side should not turn out that way. The only time I've seen something similar is in #58 but that shouldn't happen here since you are using BayesSpace functions to read data (not converting from Seurat).

A couple ideas to try:
* Turn on the `verbose = TRUE` flags in both clustering and enhancement to make sure neighbors are being detected
* Try increasing `gamma` to 3 in the enhancement
* Try more iterations. Maybe 10,000?
* Try plotting the individual clustering iterations: 
```r
clusterPlot(tmp.enhanced, mcmcChain(tmp.enhanced, "z")[1,]) #this should look exactly like your spot-level spatial clusters
clusterPlot(tmp.enhanced, mcmcChain(tmp.enhanced, "z")[2,]) #does it break down here?
clusterPlot(tmp.enhanced, mcmcChain(tmp.enhanced, "z")[3,])
```

**Comment by briglo** [comment]
Hi Thanks a tonne for getting back so quickly. I was baffled to because it worked so well out of the box on the other sections 

I tried your suggestions plus remaking the object with fewer clusters and 10k reps on the clustering. And for all i got variants of 
<img width="1194" alt="this console output while enhancing" src="https://user-images.githubusercontent.com/3935916/162104468-8ba00403-9fbe-4c84-946f-a084046980ef.png">

and 

![This output from your plot suggestions](https://user-images.githubusercontent.com/3935916/162104672-e17c33c0-ec29-4772-879b-5265cedeadf1.png)

**Comment by edward130603** [comment]
Would you be able to send me a .RDS file of your `indat` data object? For confidentiality and file size, can set `counts(indat) = NULL` and `logcounts(indat)=NULL`. I just need PCs and coordinates really. My email is ezhao(at)fredhutch[dot]org.

Not sure whether the problem is in the data our our code, but I can try to figure it out.

**Comment by briglo** [comment]
Done, thanks again ;  very much appreciated
B

**Comment by edward130603** [comment]
Thanks for sending. I think I've figured out the problem. For some reason, the row/col and imagerow/imagecol are mismatched. 

```r
library(BayesSpace)
sce = readRDS("indat_for_edward.RDS")
sce.enhanced = spatialEnhance(sce, q = length(unique(sce$spatial.cluster)),
                              verbose = T, burn.in = 100, nrep = 200)
clusterPlot(sce.enhanced)
plot(sce$imagecol~sce$col)
plot(sce$imagerow~sce$row)
plot(sce$imagecol~sce$row)
plot(sce$imagerow~sce$col)
```
![image](https://user-images.githubusercontent.com/4656221/163046715-d1f4b7c2-b760-4add-9f0d-0869f46b2089.png)

We expect row and imagerow to be linearly associated (rather than row and imagecol). So this will definitely mess up the `spatialEnhance` neighbor finding algorithm (which is different from that of `spatialCluster`, which I think is what happened to get those really scrambled looking results. This fixed it for me:

```r
#fix coordinates
sce2 = sce
sce2$imagecol.new = sce2$imagerow
sce2$imagerow = sce2$imagecol
sce2$imagecol = sce2$imagecol.new
sce.enhanced.fix = spatialEnhance(sce2, q = length(unique(sce$spatial.cluster)),
                                  verbose = T, burn.in = 100, nrep = 200)
clusterPlot(sce.enhanced.fix)
```
I'm not sure if there's some updates with SpaceRanger that caused the column switching issue. Any chance there was an issue with how SpaceRanger was run? (I don't have experience using it)

**Comment by briglo** [comment]
Thats awesome thanks so much!
![New Results are gorgeous](https://user-images.githubusercontent.com/3935916/163062278-9ef168c9-7c42-4a3b-94a4-ff76f8e9c8dd.png)

So this was run on spaceranger 1.3 and i'm willing to  bet its because the flag `--reorient-images` was used (there was some sort of issue with fiducials lining up), those image flip coords things look suspiciously familiar

Awesome to have a fix! Thanks for everything
